# Generated by Django 5.2.4 on 2025-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_simulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulatedexchange",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
