# Generated by Django 5.2.4 on 2025-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "market_data",
            "0002_dataingestionlog_exchange_fundamentaldata_industry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="yf_suffix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Yahoo Finance exchange suffix (e.g., 'AT' for Athens)",
                max_length=5,
            ),
        ),
    ]
