# Generated by Django 5.2.4 on 2025-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0002_algorithmicorder_algorithmexecution_customstrategy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithmicorder",
            name="algorithm_type",
            field=models.CharField(
                choices=[
                    ("TWAP", "Time-Weighted Average Price"),
                    ("VWAP", "Volume-Weighted Average Price"),
                    ("IS", "Implementation Shortfall"),
                    ("ICEBERG", "Iceberg Order"),
                    ("SNIPER", "Sniper Algorithm"),
                    ("POV", "Percentage of Volume"),
                    ("CUSTOM", "Custom Strategy"),
                ],
                max_length=30,
            ),
        ),
    ]
