# Generated by Django 5.2.4 on 2025-08-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0003_alter_algorithmicorder_algorithm_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remaining_quantity", models.PositiveIntegerField()),
                ("queue_position", models.PositiveIntegerField(default=0)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_queue",
                        to="order_management.orderbooklevel",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="order_management.simulatedorder",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_order_queue",
                "ordering": ["queue_position"],
                "indexes": [
                    models.Index(
                        fields=["level", "queue_position"],
                        name="simulation__level_i_a1752b_idx",
                    )
                ],
            },
        ),
    ]
