# Generated by Django 5.2.4 on 2025-08-11 12:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "benchmark_category",
                    models.CharField(
                        choices=[
                            ("EQUITY_BROAD", "Broad Equity Market"),
                            ("EQUITY_SECTOR", "Sector Equity"),
                            ("EQUITY_STYLE", "Equity Style"),
                            ("FIXED_INCOME", "Fixed Income"),
                            ("COMMODITY", "Commodity"),
                            ("CURRENCY", "Currency"),
                            ("CUSTOM", "Custom Benchmark"),
                        ],
                        default="EQUITY_BROAD",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "trading_performance_benchmarks",
            },
        ),
        migrations.CreateModel(
            name="PortfolioAnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "portfolio_metrics",
                    models.JSONField(
                        default=dict, help_text="Cached PortfolioMetrics data"
                    ),
                ),
                (
                    "position_analytics",
                    models.JSONField(
                        default=list, help_text="Cached position-level analytics"
                    ),
                ),
                (
                    "sector_allocation",
                    models.JSONField(
                        default=list, help_text="Cached sector allocation data"
                    ),
                ),
                (
                    "risk_metrics",
                    models.JSONField(
                        default=dict, help_text="Cached risk calculations"
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("calculation_duration_ms", models.IntegerField(default=0)),
                ("cache_version", models.CharField(default="1.0", max_length=20)),
                (
                    "data_freshness_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Freshness score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trading_analytics_cache",
            },
        ),
        migrations.CreateModel(
            name="RealTimeMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("snapshot_timestamp", models.DateTimeField(auto_now_add=True)),
                ("market_timestamp", models.DateTimeField()),
                (
                    "total_portfolio_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("intraday_pnl", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "intraday_pnl_percentage",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                (
                    "positions_changed",
                    models.JSONField(
                        default=list,
                        help_text="Positions that changed since last snapshot",
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        choices=[
                            ("PRICE_UPDATE", "Price Update"),
                            ("ORDER_FILL", "Order Fill"),
                            ("POSITION_CHANGE", "Position Change"),
                            ("SCHEDULED", "Scheduled Update"),
                            ("MANUAL", "Manual Refresh"),
                        ],
                        default="SCHEDULED",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trading_realtime_metrics",
                "ordering": ["-snapshot_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "snapshot_timestamp"],
                        name="trading_rea_user_id_91f371_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("CONCENTRATION_RISK", "Concentration Risk"),
                            ("HIGH_VOLATILITY", "High Volatility"),
                            ("DRAWDOWN_ALERT", "Drawdown Alert"),
                            ("VAR_BREACH", "VaR Breach"),
                            ("CORRELATION_RISK", "Correlation Risk"),
                            ("LIQUIDITY_RISK", "Liquidity Risk"),
                            ("POSITION_LIMIT", "Position Limit Breach"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                ("affected_symbols", models.JSONField(default=list)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_time_risk_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trading_real_time_risk_alerts",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="trading_rea_user_id_7a91ba_idx"
                    ),
                    models.Index(
                        fields=["alert_type", "severity"],
                        name="trading_rea_alert_t_9c07c7_idx",
                    ),
                    models.Index(
                        fields=["triggered_at"], name="trading_rea_trigger_ac6380_idx"
                    ),
                ],
            },
        ),
    ]
